theme: jekyll-theme-tactile
plugins:
  - jekyll-feed
 
incremental: true
name: ReleaseStandard's blog
description: Various stuff not well organized
feed:
  posts_limit: 20

include:  
  - _pages
         
tags:
